# Site settings
title: "Meichen Fang"
description: "Personal Website"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://meichenfang.github.io" # the base hostname & protocol for your site

# Author information
author:
  name: "Meichen Fang"
  email: "mffang@caltech.edu"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal # Example of using a Jekyll theme
permalink: pretty # Pretty URLs without file extensions

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # Add other plugins as needed

